version: "3.8"
  
services:
  develop_server:
    image: 1569663570/openeuler_develop_server
    restart: always
    container_name: develop_server
    hostname: develop_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.2
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      
  web_server:
    image: 1569663570/openeuler_web_server
    restart: always
    container_name: web_server
    hostname: web_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.6    
    ports:
      - 6680:80
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区      
      MARIADB_SERVER: mariadb_server      
      MARIADB_USER: teamtalk
      MARIADB_PASSWORD: teamtalk123@
      MARIADB_DATABASE: teamtalk
      MSFS_URL: msfs_server:8700
      HTTP_URL: http_msg_server:8400    
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  login_server:
    image: 1569663570/openeuler_login_server
    restart: always
    container_name: login_server
    hostname: login_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.10
    ports:
      - 8080:8080
      - 8008:8008
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      MSFS_SERVER: msfs_server
      WEB_SERVER: web_server
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  msg_server:
    image: 1569663570/openeuler_msg_server
    restart: always
    container_name: msg_server
    hostname: msg_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.17
    ports:
      - 8000:8000
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      IP_ADDR1: 192.168.0.88
      IP_ADDR2: 192.168.1.88
      DB_PROXY_SERVER: db_proxy_server
      LOGIN_SERVER: login_server
      ROUTE_SERVER: route_server
      PUSH_SERVER: push_server
      FILE_SERVER: file_server
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  db_proxy_server:
    image: 1569663570/openeuler_db_proxy_server
    restart: always
    container_name: db_proxy_server
    hostname: db_proxy_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.16
    ports:
      - 10600:10600
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      MARIADB_SERVER_MASTER: mariadb_server
      MARIADB_SERVER_SLAVE: mariadb_server
      MARIADB_USER: teamtalk
      MARIADB_PASSWORD: teamtalk123@      
      MARIADB_DATABASE: teamtalk
      UNREAD_HOST: redis_server
      GROUP_SET_HOST: redis_server
      SYNC_HOST: redis_server
      TOKEN_HOST: redis_server
      GROUP_MEMBER_HOST: redis_server
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  route_server:
    image: 1569663570/openeuler_route_server
    restart: always
    container_name: route_server
    hostname: route_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.15
    ports:
      - 8200:8200
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  http_msg_server:
    image: 1569663570/openeuler_http_msg_server
    restart: always
    container_name: http_msg_server
    hostname: http_msg_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.14
    ports:
      - 8400:8400
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      DB_SERVER_IP1: db_proxy_server
      ROUTE_SERVER_IP1: route_server
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  push_server:
    image: 1569663570/openeuler_push_server
    restart: always
    container_name: push_server
    hostname: push_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.13
    ports:
      - 8500:8500
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  file_server:
    image: 1569663570/openeuler_file_server
    restart: always
    container_name: file_server
    hostname: file_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.12
    ports:
      - 8600:8600
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  msfs_server:
    image: 1569663570/openeuler_msfs_server
    restart: always
    container_name: msfs_server
    hostname: msfs_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.11
    ports:
      - 8700:8700
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:      
      - redis_server
      - mariadb_server

  mariadb_server:
    image: library/mariadb:10.7.1
    restart: always
    container_name: mariadb_server
    hostname: mariadb_server
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ../auto_setup/mariadb/conf:/docker-entrypoint-initdb.d
    networks:
      teamtalk:
        ipv4_address: 6.1.0.8
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      MARIADB_ROOT_PASSWORD: admin123@
      MARIADB_DATABASE: teamtalk
      MARIADB_USER: teamtalk
      MARIADB_PASSWORD: teamtalk123@
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"

  redis_server:
    image: 1569663570/openeuler_redis_server
    restart: always
    container_name: redis_server
    hostname: redis_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.7
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      BIND: 0.0.0.0
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"

networks:
  teamtalk:
    driver: bridge
    ipam:
      config:
        - subnet: 6.1.0.0/16
          gateway: 6.1.0.1